In [ ]:
#example with Python
#reading data from a file

In [2]:
# Load the Pandas libraries with alias 'pd' 
import pandas as pd 

# Read data from file 'geometryITS.csv' 
# (in the same directory that your python process is based)
 
data = pd.read_csv("geometryITS.csv") 


# Preview the first 5 lines of the loaded data 
data.head()

,Row,Sample,Anon Student Id,Problem Hierarchy,Problem Name,Problem View,Step Name,Step Start Time,First Transaction Time,Correct Transaction Time,...,Step Duration (sec),Correct Step Duration (sec),Error Step Duration (sec),First Attempt,Incorrects,Hints,Corrects,Condition,KC,Opportunity
0,1,All Data,Stu_02ee1b3f31a6f6a7f4b8012298b2395e,Unit Area,RECTANGLE_ABCD,1,(AREA QUESTION1),02/01/1996 00:00,02/01/1996 00:00,02/01/1996 00:00,...,0,0,.,correct,0,0,1,.,Non-area formula,1
1,2,All Data,Stu_02ee1b3f31a6f6a7f4b8012298b2395e,Unit Area,RECTANGLE_ABCD,1,(HEIGHT QUESTION2),02/01/1996 00:00,02/01/1996 00:02,02/01/1996 00:02,...,128,128,.,correct,0,0,1,.,Non-area formula,2
2,3,All Data,Stu_02ee1b3f31a6f6a7f4b8012298b2395e,Unit Area,RECTANGLE_ABCD,1,(BASE QUESTION3),02/01/1996 00:02,02/01/1996 00:03,02/01/1996 00:03,...,29,29,.,correct,0,0,1,.,Non-area formula,3
3,4,All Data,Stu_02ee1b3f31a6f6a7f4b8012298b2395e,Unit Area,BUILDING_A_SIDEWALK,1,(POOL-AREA QUESTION1),02/01/1996 00:04,02/01/1996 00:04,02/01/1996 00:04,...,0,0,.,correct,0,0,1,.,Non-area formula,4
4,5,All Data,Stu_02ee1b3f31a6f6a7f4b8012298b2395e,Unit Area,BUILDING_A_SIDEWALK,1,(LARGE-RECTANGLE-AREA QUESTION1),02/01/1996 00:04,02/01/1996 00:04,02/01/1996 00:04,...,12,12,.,correct,0,0,1,.,Non-area formula,5

In [ ]:
#view all variables that are recorded in the dataset